In [16]:
import numpy as np

# Библиотека numpy


## Суммы Эйнштейна

С помощью соглашения Эйнштейна о суммировании, многие общие многомерные линейные алгебраические операции с массивами могут быть представлены простым способом.

`Если одна и та же буква в обозначении индекса встречается и сверху, и снизу, то такой член полагается просуммированным по всем значениям, которые может принимать этот индекс. `

Например, выражение $c_j = a_i b^i_j$ понимается как $c_j = \sum_{i=1}^n a_i b^i_j$.

Подобные операции часто возникают в анализе данных, в особенности при реализации байесовских методов.

В `numpy` такие операции реализует функция `einsum`, причем здесь не делается разницы между нижними и верхними индексами. Функция принимает на вход сигнатуру операции в виде текстовой строки и матрицы с данными.

Разберем на примере выше. В данном случае сигнатура имеет вид `i,ji->j`. Элементы сигнатуры последовательно означают следующее (тензор = многомерная матрица):
* `i` --- объявление обозначений индексов тензора $A$. Поскольку индекс один, то тем самым $A$ должен быть вектором.
* `,` --- переход к объявлению индексов следующему тензору.
* `ji` --- объявление обозначений индексов тензора $B$. Поскольку индекса два, то тем самым $B$ должен быть матрицей.
* `->` --- разграничение входа и выхода.
* `j` --- индекс на выходе. Поскольку индекс $i$ объявлен на входе и не объявлен на выходе, по нему происходит суммирование поэлементных произведений.

In [17]:
A = np.array([0, 1, 2])
B = np.array([[10, 15, 20], [100, 150, 200]])
print(A)
print(B)

[0 1 2]
[[ 10  15  20]
 [100 150 200]]


$c_0 = a_0 \cdot b^0_0 + a_1 \cdot b^1_0 + a_2 \cdot b^2_0$. В нашем случае: $c_0 = 0 \cdot 10 + 1 \cdot 15 + 2 \cdot 20$  
$c_1 = a_0 \cdot b^0_1 + a_1 \cdot b^1_1 + a_2 \cdot b^2_1$. В нашем случае: $c_1 = 0 \cdot 100 + 1 \cdot 150 + 2 \cdot 200$  

In [18]:
np.einsum('i,ji->j', A, B)

array([ 55, 550])

Суммирование элементов вектора $A$

In [19]:
np.einsum('i->', A)

3

Суммирование элементов матрицы $B$ по столбцам

In [20]:
np.einsum('ji->i', B)

array([110, 165, 220])

Рассмотрим следующие матрицы

In [21]:
A = np.array([[0, 1, 2], [3, 4, 5]])
B = np.array([[0, 1], [10, 100], [30, 70]])
print(A)
print(B)

[[0 1 2]
 [3 4 5]]
[[  0   1]
 [ 10 100]
 [ 30  70]]


Транспонирование матрицы $A$

In [22]:
np.einsum('ij->ji', A) 

array([[0, 3],
       [1, 4],
       [2, 5]])

Матричное умножение

In [23]:
np.einsum('ij,jk->ik', A, B) 

array([[ 70, 240],
       [190, 753]])

Можно наоборот

In [24]:
np.einsum('jk,ij->ik', B, A) 

array([[ 70, 240],
       [190, 753]])

Квадратная матрица

In [25]:
C = np.arange(9).reshape((3, 3))
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Диагональ

In [26]:
np.einsum('ii->i', C)

array([0, 4, 8])

След

In [27]:
np.einsum('ii->', C)

12

Какая-то странная операция

In [28]:
np.einsum('ij,kj,jl->ilk', A, C, B) 

array([[[ 130,  340,  550],
        [ 380, 1100, 1820]],

       [[ 340,  910, 1480],
        [1100, 3359, 5618]]])

**Упражнение.** Создайте матрицы $A\in\mathbb{R}^{3\times2}, B\in\mathbb{R}^{2\times2}$. Посчитайте $\text{tr} (ABBA^T)$

-----

Введение в анализ данных, 2020

<a href="https://mipt-stats.gitlab.io">mipt-stats.gitlab.io</a>